version: '3.1'

# WARNING: this docker compose it's only for development purpose and thus it's
# not suitable for production environments!
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: a123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: a123

  roulette:
    build: .
    restart: always
    ports:
      - 57684:80
    environment:
      ROULETTE_DATABASE_IP: mongo
      ROULETTE_DATABASE_USERNAME: test
      ROULETTE_DATABASE_PASSWORD: a123